---
format: pdf
editor: visual
bibliography: references.bib
csl: ecology.csl
---

## Relationship between frog size and weight in the Sierra Nevada yellow-legged frog, *Rana sierrae*

Jane Q. Johnson^1\*^, Ned R. Nichols^2^

^1^ University of California, Santa Barbara

^2^ University of Colorado, Boulder

\* Corresponding author: jqjohnson\@gmail.com

### Abstract

### Introduction

### Methods and Materials

We captured xx post-metamorphic *R. sierrae* (hereafter, "frogs") from Mesa Lake, Sierra National Forest, on August 15, 2023.
Frog snout-vent length was measured to the nearest millimeter using digital calipers and frogs were weighed to the nearest gram using a spring scale.
To describe the relationship between length and weight, we plotted log~10~(frog weight) against log~10~(frog length).

### Results

The relationship between frog length and weight was linear on a log~10~ scale and showed little scatter around the regression line.

```{r}
#| echo: false
#| warning: false

# Load required packages
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(here, tidyverse)

# Read in dataset
options(readr.show_col_types = FALSE)
len_wt <- read_csv(here("Workshop_2", "data", "len_wt.csv"))

# Create plot
len_wt <- len_wt %>% 
  mutate(loglength = log10(length), 
         logweight = log10(weight))

ggplot(data = len_wt, aes(x = length, y = weight)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_x_log10("Snout-vent length (mm)") +
  scale_y_log10("Weight (g)")

ggsave


```
